# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += push.o

# added by M-R-VulkaN for testing
CFLAGS += -DDECK_FORCE=emergency_land
DEBUG=1 

CRAZYFLIE_BASE=../../..
include $(CRAZYFLIE_BASE)/Makefile
