#ifndef __OXYGEN_SENSOR_H__
#define __OXYGEN_SENSOR_H__

#define OXYGEN_SENSOR_CHECK_FREQUENCY 3

#define OXYGEN_SENSOR_VID 1
#define OXYGEN_SENSOR_PID 11

#define TASK_SIZE configMINIMAL_STACK_SIZE

#define TASK_PRIORITY 3

#define OXYGEN_SENSOR_PIN DECK_GPIO_MISO //The STM pin used to receive the signal from the NRF
#define OXYGEN_SENSOR_PIN_USING DECK_USING_PA6

#define STM32_VREF_VOLTS 3.0
#define STM32_ANALOG_BIT_BASE 4095
#define OXYGEN_SENSOR_CONSTANT (0.21 / 2.0)
#define OXYGEN_SENSOR_CORRECTION_CONSTANT (-5.730121999999991)

#endif //__OXYGEN_SENSOR_H__
